### ISSUE TITLE
Error when creating cloud scheduler

### ISSUE THREAD

**Issue by Technical-Analytics-Implementation** [google/analytics-settings-database#2]
Hey there! 

I did my best to avoid submitting a request but I wanted to reach out. The steps I've taken include deleting my first staging project and creating a new staging project just to make sure I didn't miss a step in the process. 

I am getting two errors at the last stage of the script when it tries to create a `cloud scheduler.` See the errors below and the screenshot here https://d.pr/i/BrTjGp .

```
ERROR: (gcloud.app.create) The project [myproject-name] already contains an App Engine application in region [us-central].  You can deploy your application using `gcloud app deploy`.
ERROR: (gcloud.scheduler.jobs.create.http) argument --uri: Bad value []: Must be a valid HTTP or HTTPS URL.
```

I am using a brand new project to test out the script prior to installing on a production project. 

I hope this is enough information to get started. Let me know if I should provide more details. 

Thank you.

**Comment by b-kuehn** [comment]
The latest updates fix this issue since the deploy script no longer creates the scheduler and users are instructed to use the Google Cloud UI.
